export default {
  LOGIN: '/',
  OVERVIEW: '/overview',
  CUSTOMER: '/customer',
  INVOICE: '/invoice',
  PRODUCT: '/product',
  SUPPLIER: '/supplier',
  RECEIPT: '/receipt',
  PAYMENT: '/payment',
  PURCHASE: '/purchase',
  ALL_PURCHASES: '/all-purchases',
  SALES: '/sales',
  USER: '/user',
  EXPENSE: '/expense',
  STORE_INFO: '/store-info',
};
